// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjihfzitkehyaiznpjnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqaWhmeml0a2VoeWFpem5wam5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4Mzk3NjUsImV4cCI6MjA3NDQxNTc2NX0.0lXicrC1ivejS1bj6K6uKUaxfaNXe7YWocD2yB-fKME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});